### ISSUE TITLE
If run without <what>, default to current working directory

### ISSUE THREAD

**Issue by bnb** [pkgjs/detect-node-support#63]
Looking into using this a bit as an alternative to my own [mingine](https://github.com/cutenode/mingine) and realized that simply running `npx detect-node-support` doesn't actually do anything other than output help.

It would be a nice tiny DX enhancement if running it simply assumed `<what>` was the current working directory. Since the `<command>` is implicit in detect-node-support, it makes sense to assume that simply running the tool will give you the output of it in your current working directory, much like `npm install` or `webpack`.

**Comment by dominykas** [comment]
Good catch - thanks. The README already says that it should work off cwd when no arg given, so I guess that was my intent anyways 👍
